# basic options
title: Holtz Data
author: L. Holtz
email: ljholtz10@gmail.com
description: A wonderful site
twitter_username: "@LjHo1tz"
github_username:  LHoltz

# Build settings
markdown: kramdown
theme: minima
